# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_developer',
            field=models.NullBooleanField(help_text='I am a developer'),
        ),
    ]
