# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 09:42
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(code='nomatch', message='The name has to be atleast 3 characters long!', regex='^.{3}$')])),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.FloatField(help_text='Price of the game', validators=[django.core.validators.MinValueValidator(0)])),
                ('saleprice', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('onsale', models.BooleanField()),
                ('soldcopies', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
