# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 13:57
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(code='nomatch', message='The name has to be atleast 3 characters long!', regex='^.{3}$')])),
                ('developer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('price', models.FloatField(help_text='Price of the game', validators=[django.core.validators.MinValueValidator(0)])),
                ('saleprice', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('onsale', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
