# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 11:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_boughtgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 17, 11, 42, 44, 26866, tzinfo=utc)),
        ),
    ]
