# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_game_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
