# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180217_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='user_pictures'),
        ),
    ]
