# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20180214_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='developer',
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
