# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180220_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.FileField(default='', upload_to='game_pictures'),
        ),
    ]
