# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 19:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180220_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default='', upload_to='game_pictures'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
