# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180220_1828'),
        ('main', '0009_auto_20180220_2106'),
    ]

    operations = [
    ]
