# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_20180220_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default='', upload_to='game_pictures'),
        ),
    ]
