# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_buydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buydate',
            name='date',
        ),
        migrations.DeleteModel(
            name='BuyDate',
        ),
    ]
