# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
