# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20180218_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/def_userpic.jpg', null=True, upload_to='user_pictures'),
        ),
    ]
