# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20180220_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='mm/dd/yyyy or yyyy-mm-dd', null=True),
        ),
    ]
